//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Server
{
    using System;
    
    public partial class Adresa
    {
        public string Ulica { get; set; }
        public string Grad { get; set; }
        public int Broj { get; set; }
        public int PostanskiBroj { get; set; }
    }
}
