//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Server
{
    using System;
    
    public partial class Broj_telefona
    {
        public int Pozivni_broj { get; set; }
        public int Okrug { get; set; }
        public int Broj { get; set; }
    }
}
