//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Server
{
    using System;
    using System.Collections.Generic;
    
    public partial class Posjeduje
    {
        public long Vlasnik_racunaraJMBG_vl { get; set; }
        public int RacunarID_racunara { get; set; }
    
        public virtual Vlasnik_racunara Vlasnik_racunara { get; set; }
        public virtual Racunar Racunar { get; set; }
    }
}
