//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Server
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ProjectDbContext : DbContext
    {
        public ProjectDbContext()
            : base("name=ProjectDbContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Vlasnik_racunara> Vlasnik_racunaraSet { get; set; }
        public virtual DbSet<Racunar> RacunarSet { get; set; }
        public virtual DbSet<Posjeduje> PosjedujeSet { get; set; }
        public virtual DbSet<Servis> ServisSet { get; set; }
        public virtual DbSet<Komponenta> KomponentaSet { get; set; }
        public virtual DbSet<Sastoji_se> Sastoji_seSet { get; set; }
        public virtual DbSet<Donosi> DonosiSet { get; set; }
        public virtual DbSet<Serviser_racunara> Serviser_racunaraSet { get; set; }
        public virtual DbSet<Radi> RadiSet { get; set; }
        public virtual DbSet<Servisira> ServisiraSet { get; set; }
        public virtual DbSet<Garantni_list> Garantni_listSet { get; set; }
        public virtual DbSet<Racunarski_servis> Racunarski_ServisSet { get; set; }
    }
}
