//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Server
{
    using System;
    using System.Collections.Generic;
    
    public partial class Racunar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Racunar()
        {
            this.Komponenta = new HashSet<Komponenta>();
            this.Posjeduje = new HashSet<Posjeduje>();
        }
    
        public int ID_racunara { get; set; }
        public string Proizvodjac { get; set; }
        public double Brzina_procesora { get; set; }
        public int Kapacitet_RAM { get; set; }
        public int Kapacitet_memorije { get; set; }
        public Vrsta_racunara Vrsta_racunara { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Komponenta> Komponenta { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Posjeduje> Posjeduje { get; set; }
    }
}
