//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Server
{
    using System;
    using System.Collections.Generic;
    
    public partial class Radi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Radi()
        {
            this.Servisira = new HashSet<Servisira>();
        }
    
        public int Racunarski_servisID_servisa { get; set; }
        public long Serviser_racunaraJMBG_s { get; set; }
    
        public virtual Racunarski_servis Racunarski_servis { get; set; }
        public virtual Serviser_racunara Serviser_racunara { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Servisira> Servisira { get; set; }
    }
}
