//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Server
{
    using System;
    using System.Collections.Generic;
    
    public partial class Servisira
    {
        public double Cijena_serv { get; set; }
        public System.DateTime Dat_potp { get; set; }
        public int RadiRacunarski_servisID_servisa { get; set; }
        public long RadiServiser_racunaraJMBG_s { get; set; }
        public int DonosiRacunarski_servisID_servisa { get; set; }
        public long DonosiPosjedujeVlasnik_racunaraJMBG_vl { get; set; }
        public int DonosiPosjedujeRacunarID_racunara { get; set; }
        public Nullable<int> Garantni_listId_gar_list { get; set; }
    
        public virtual Radi Radi { get; set; }
        public virtual Donosi Donosi { get; set; }
        public virtual Garantni_list Garantni_list { get; set; }
    }
}
