//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Server
{
    using System;
    
    public partial class SqlUpitVlasnikServisCijena
    {
        public string Ime { get; set; }
        public string Prezime { get; set; }
        public string Naziv_servisa { get; set; }
        public long JMBG_vlasnika { get; set; }
        public double Cijena { get; set; }
    }
}
